[package]
name = "ime"
version = "1.0.0"
edition = "2024"
rust-version = "1.85"
authors = ["Dawid Wasowski <contact@dav.one>"]
description = "A fast, lightweight CLI for reading, writing, and wiping metadata from image files."
readme = "README.md"
license = "CC-BY-NC-4.0"
categories = ["command-line-utilities", "multimedia::images", "development-tools", "multimedia", "utilities"]
keywords = ["cli", "metadata", "exif", "image", "tool"]
publish = false

[dependencies]
crc = "3.4.0"
lexopt = "0.3.2"
little_exif = "0.6.23"
nom-exif = { version = "3", default-features = false }
serde_json = "1.0.151"

[dev-dependencies]
assert_cmd = "2.2.2"
predicates = "3.1.4"
tempfile = "3.27.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
strip = true
panic = "abort"
